theme: osuny
_merge: deep
params:
  plausible: levelesyeux.com
  logo:
    header: "/assets/images/logo.png"
    footer: "/assets/images/logo.png"
  breadcrumb:
    position: after-hero
  summary:
    position: hero
  search:
    active: true
  debug:
     productionUrl: "https://www.levelesyeux.com"
  home:
    head:
      title: site